doc: modifed the reaction-search documentation
cheminfo/c6h6-documentation pull request #21
Opened 2021-04-25 20:11 UTC by KrittapasJ

- Added images
- Modified documentation
- Remove incorrect information

2021-05-02 09:31 UTC, kjappelbaum commented
are there some bugs you found in the view?

2021-05-02 10:38 UTC, KrittapasJ commented
I don't think so.

Set



Sent from my Galaxy



-------- Original message --------
From: Kevin Jablonka ***@***.***>
Date: 5/2/21 11:32 (GMT+01:00)
To: cheminfo/c6h6-documentation ***@***.***>
Cc: Jantarug Krittapas ***@***.***>, Author ***@***.***>
Subject: Re: [cheminfo/c6h6-documentation] doc: modifed the reaction-search documentation (#21)


are there some bugs you found in the view?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/cheminfo/c6h6-documentation/pull/21#issuecomment-830779002>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATXO2VA64RWAYVKYXZXE27DTLULY5ANCNFSM43RT5ZGA>.

2021-05-11 19:16 UTC, kjappelbaum requested changes
besides the comments lgtm

2021-05-11 19:16 UTC, kjappelbaum commented on src/book/eln/eln-search/README.md
> +- `similarity` : search for samples with a similar structure.
can you define similarity

2021-05-11 19:16 UTC, kjappelbaum commented on src/book/eln/eln-search/README.md
> +You can also know which of the interested structure is reagent or product by checking the right two columns.
seems here is a typo "interested structure"

2021-06-02 13:56 UTC, KrittapasJ commented
Hi Kevin,

I change “ interested structure" to be "structure of interest” already. Is it better?
According to definition of similarity, I try to study this mode but I am actually not sure about definition of it. Could you please explain more about similarity mode?
Thank you in advance

Sincerely,
Set

On 11 May 2564 BE, at 21:17, Kevin Jablonka ***@***.******@***.***>> wrote:



@kjappelbaum requested changes on this pull request.

besides the comments lgtm

________________________________

In src/book/eln/eln-search/README.md<https://github.com/cheminfo/c6h6-documentation/pull/21#discussion_r630454465>:

>
-Double clicking a row in the center module will take you directly to the first matching sample.
+- `substructure` : search for samples containing the given substructure
+- `similarity` : search for samples with a similar structure.


can you define similarity

________________________________

In src/book/eln/eln-search/README.md<https://github.com/cheminfo/c6h6-documentation/pull/21#discussion_r630454813>:

>
-Double clicking a row in the center module will take you directly to the first matching sample.
+- `substructure` : search for samples containing the given substructure
+- `similarity` : search for samples with a similar structure.
+
+Then, draw a structure in the left module.
+
+![Left module](images/leftmodule.png)
+
+The list of matching structures would be displayed at the center module.
+You can also know which of the interested structure is reagent or product by checking the right two columns.


seems here is a typo "interested structure"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/cheminfo/c6h6-documentation/pull/21#pullrequestreview-657111129>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATXO2VAMJTZATRMKOUD73J3TNF7DZANCNFSM43RT5ZGA>.

2021-06-21 07:51 UTC, KrittapasJ commented
Hi Kevin,

During last class, I was asking about the definition of similarity for reaction search, Luc found that it might be a bug of this mode. So, what should I do next?
Thank you in advance.

Sincerely

Set

On 11 May 2564 BE, at 21:17, Kevin Jablonka ***@***.******@***.***>> wrote:



@kjappelbaum requested changes on this pull request.

besides the comments lgtm

________________________________

In src/book/eln/eln-search/README.md<https://github.com/cheminfo/c6h6-documentation/pull/21#discussion_r630454465>:

>
-Double clicking a row in the center module will take you directly to the first matching sample.
+- `substructure` : search for samples containing the given substructure
+- `similarity` : search for samples with a similar structure.


can you define similarity

________________________________

In src/book/eln/eln-search/README.md<https://github.com/cheminfo/c6h6-documentation/pull/21#discussion_r630454813>:

>
-Double clicking a row in the center module will take you directly to the first matching sample.
+- `substructure` : search for samples containing the given substructure
+- `similarity` : search for samples with a similar structure.
+
+Then, draw a structure in the left module.
+
+![Left module](images/leftmodule.png)
+
+The list of matching structures would be displayed at the center module.
+You can also know which of the interested structure is reagent or product by checking the right two columns.


seems here is a typo "interested structure"

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/cheminfo/c6h6-documentation/pull/21#pullrequestreview-657111129>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATXO2VAMJTZATRMKOUD73J3TNF7DZANCNFSM43RT5ZGA>.

2021-06-22 07:47 UTC, kjappelbaum commented
don't worry about this bug for the course.

2021-06-22 08:15 UTC, kjappelbaum approved these changes

2021-06-22 08:16 UTC, merged