docs: update IR documentation
cheminfo/c6h6-documentation pull request #25
Opened 2021-05-11 18:20 UTC by Ali-Abikhodr

2021-05-11 19:19 UTC, kjappelbaum requested changes
Looking at the other IR tips/documentation pages it seems that there are some typos and that some of them could still use a n image. Would be great if you could add something there.

2021-05-11 19:19 UTC, kjappelbaum commented on src/book/spectra/ir/view-and-process-ir/IRCompare/index.md
> +Afterwhich, under __List of selected enteries__ (1), you can choose the other molecule which has the spectrum that you would like to compare. Then choose the IR spectrum you would like to be plotted
please fix the typos

2021-06-16 12:43 UTC, Ali-Abikhodr commented on src/book/spectra/ir/view-and-process-ir/IRCompare/index.md
> +Afterwhich, under __List of selected enteries__ (1), you can choose the other molecule which has the spectrum that you would like to compare. Then choose the IR spectrum you would like to be plotted
hello, i did a while back and i thought that commiting on visual studio will automatically update my older pull rquest, sorry it is now 2 pull requests

2021-06-22 07:45 UTC, kjappelbaum commented
duplicated in #26

2021-06-22 07:45 UTC, closed without merging